pragma Singleton

import QtQuick
import Quickshell

Singleton {
    id: root

    readonly property url fontSource: Qt.resolvedUrl("../assets/icons/font/fonts/Font.ttf")
    readonly property string fallbackFamily: "Untitled"
    readonly property string family: iconFont.name.length ? iconFont.name : fallbackFamily

    FontLoader {
        id: iconFont

        source: root.fontSource
    }

    readonly property string wifiZero: "\uf000" // wifi-zero
    readonly property string wifiSync: "\uf003" // wifi-sync
    readonly property string wifiPen: "\uf004" // wifi-pen
    readonly property string wifiOff1: "\uf005" // wifi-off1
    readonly property string wifiLow: "\uf006" // wifi-low
    readonly property string wifiHigh: "\uf007" // wifi-high
    readonly property string wifiCog: "\uf008" // wifi-cog
    readonly property string wifi1: "\uf00c" // wifi1
    readonly property string usb: "\uf4df" // usb
    readonly property string upload: "\uf0c2" // upload
    readonly property string unlink: "\uf1d0" // unlink
    readonly property string unlink2: "\uf031" // unlink-2
    readonly property string sunset: "\uf28a" // sunset
    readonly property string sword: "\uf07f" // sword
    readonly property string globeLock: "\uf414" // globe-lock
    readonly property string globe: "\uf0fd" // globe
    readonly property string glasses: "\uf2ad" // glasses
    readonly property string captions: "\uf4a4" // captions
    readonly property string captionsOff: "\uf22d" // captions-off
    readonly property string briefcaseBusiness: "\uf585" // briefcase-business
    readonly property string botOff: "\uf3d3" // bot-off
    readonly property string botMessageSquare: "\uf4f1" // bot-message-square
    readonly property string bot: "\uf36e" // bot
    readonly property string bookmarkX: "\uf2a7" // bookmark-x
    readonly property string bookmarkPlus: "\uf1b4" // bookmark-plus
    readonly property string bookmarkMinus: "\uf388" // bookmark-minus
    readonly property string bookmarkCheck: "\uf0c0" // bookmark-check
    readonly property string bookmark: "\uf0ae" // bookmark
    readonly property string bookHeadphones: "\uf0ee" // book-headphones
    readonly property string bluetoothSearching: "\uf25a" // bluetooth-searching
    readonly property string bluetoothOff: "\uf582" // bluetooth-off
    readonly property string bluetoothConnected: "\uf237" // bluetooth-connected
    readonly property string bluetooth: "\uf2ff" // bluetooth
    readonly property string printer: "\uf234" // printer
    readonly property string rocket: "\uf0ac" // rocket
    readonly property string stepForward: "\uf33f" // step-forward
    readonly property string stepBack: "\uf45c" // step-back
    readonly property string starOff: "\uf4d3" // star-off
    readonly property string starHalf: "\uf338" // star-half
    readonly property string star: "\uf1e4" // star
    readonly property string sun: "\uf1dc" // sun
    readonly property string thermometer: "\uf350" // thermometer
    readonly property string thermometerSnowflake: "\uf3f9" // thermometer-snowflake
    readonly property string thermometerSun: "\uf190" // thermometer-sun
    readonly property string thumbsUp: "\uf264" // thumbs-up
    readonly property string thumbsDown: "\uf3d7" // thumbs-down
    readonly property string toggleRight: "\uf549" // toggle-right
    readonly property string toggleLeft: "\uf495" // toggle-left
    readonly property string timerReset: "\uf259" // timer-reset
    readonly property string timerOff: "\uf528" // timer-off
    readonly property string timer: "\uf036" // timer
    readonly property string triangleAlert: "\uf5b1" // triangle-alert
    readonly property string trash2: "\uf182" // trash-2
    readonly property string trash: "\uf202" // trash
    readonly property string umbrellaOff: "\uf169" // umbrella-off
    readonly property string umbrella: "\uf53c" // umbrella
    readonly property string undo2: "\uf45e" // undo-2
    readonly property string unplug: "\uf239" // unplug
    readonly property string vote: "\uf3d4" // vote
    readonly property string volumeX: "\uf0dc" // volume-x
    readonly property string volume2: "\uf5ac" // volume-2
    readonly property string volume1: "\uf551" // volume-1
    readonly property string volume: "\uf395" // volume
    readonly property string watch: "\uf2ec" // watch
    readonly property string zoomOut: "\uf267" // zoom-out
    readonly property string zoomIn: "\uf2b3" // zoom-in
    readonly property string zapOff: "\uf452" // zap-off
    readonly property string wifiOff: "\uf1fd" // wifi-off
    readonly property string wifi: "\uf2f1" // wifi
    readonly property string space: "\uf3e9" // space
    readonly property string spellCheck: "\uf08e" // spell-check
    readonly property string speaker: "\uf243" // speaker
    readonly property string sparkle: "\uf4c5" // sparkle
    readonly property string sparkles: "\uf46f" // sparkles
    readonly property string soup: "\uf2c4" // soup
    readonly property string smile: "\uf288" // smile
    readonly property string slidersVertical: "\uf45f" // sliders-vertical
    readonly property string slidersHorizontal: "\uf407" // sliders-horizontal
    readonly property string skipForward: "\uf397" // skip-forward
    readonly property string skipBack: "\uf180" // skip-back
    readonly property string shuffle: "\uf0ce" // shuffle
    readonly property string signalZero: "\uf092" // signal-zero
    readonly property string signalMedium: "\uf1da" // signal-medium
    readonly property string signalLow: "\uf57f" // signal-low
    readonly property string signalHigh: "\uf368" // signal-high
    readonly property string iconSignal: "\uf491" // signal
    readonly property string shipWheel: "\uf480" // ship-wheel
    readonly property string shieldX: "\uf36c" // shield-x
    readonly property string shieldQuestion: "\uf0de" // shield-question
    readonly property string shieldPlus: "\uf4ee" // shield-plus
    readonly property string shieldOff: "\uf01f" // shield-off
    readonly property string shieldMinus: "\uf31b" // shield-minus
    readonly property string shieldEllipsis: "\uf439" // shield-ellipsis
    readonly property string shieldCheck: "\uf05a" // shield-check
    readonly property string shieldBan: "\uf04e" // shield-ban
    readonly property string shieldAlert: "\uf216" // shield-alert
    readonly property string shield: "\uf3b8" // shield
    readonly property string settings2: "\uf355" // settings-2
    readonly property string settings: "\uf3dc" // settings
    readonly property string serverOff: "\uf28d" // server-off
    readonly property string serverCrash: "\uf1ab" // server-crash
    readonly property string serverCog: "\uf159" // server-cog
    readonly property string server: "\uf39d" // server
    readonly property string searchX: "\uf0b7" // search-x
    readonly property string searchSlash: "\uf26d" // search-slash
    readonly property string searchCode: "\uf287" // search-code
    readonly property string searchCheck: "\uf2af" // search-check
    readonly property string search: "\uf5ae" // search
    readonly property string scrollText: "\uf17e" // scroll-text
    readonly property string scroll: "\uf249" // scroll
    readonly property string screenShareOff: "\uf4bc" // screen-share-off
    readonly property string screenShare: "\uf00a" // screen-share
    readonly property string rows4: "\uf02d" // rows-4
    readonly property string rows3: "\uf0fa" // rows-3
    readonly property string rows2: "\uf106" // rows-2
    readonly property string rss: "\uf2f5" // rss
    readonly property string router: "\uf174" // router
    readonly property string routeOff: "\uf588" // route-off
    readonly property string route: "\uf0f4" // route
    readonly property string rotateCwSquare: "\uf1a2" // rotate-cw-square
    readonly property string rotateCw: "\uf4c0" // rotate-cw
    readonly property string rotateCcw: "\uf30c" // rotate-ccw
    readonly property string rectangleVertical: "\uf151" // rectangle-vertical
    readonly property string rectangleHorizontal: "\uf054" // rectangle-horizontal
    readonly property string rectangleEllipsis: "\uf50a" // rectangle-ellipsis
    readonly property string rewind: "\uf0c4" // rewind
    readonly property string replyAll: "\uf18d" // reply-all
    readonly property string reply: "\uf54d" // reply
    readonly property string redo2: "\uf4cc" // redo-2
    readonly property string repeat2: "\uf429" // repeat-2
    readonly property string repeat1: "\uf3be" // repeat-1
    readonly property string refreshCwOff: "\uf3c4" // refresh-cw-off
    readonly property string repeat: "\uf55c" // repeat
    readonly property string refreshCcwDot: "\uf42c" // refresh-ccw-dot
    readonly property string refreshCw: "\uf422" // refresh-cw
    readonly property string refreshCcw: "\uf2cb" // refresh-ccw
    readonly property string radioTower: "\uf351" // radio-tower
    readonly property string radioReceiver: "\uf2d4" // radio-receiver
    readonly property string radio: "\uf37f" // radio
    readonly property string powerOff: "\uf0e9" // power-off
    readonly property string power: "\uf4a8" // power
    readonly property string pointerOff: "\uf136" // pointer-off
    readonly property string pointer: "\uf545" // pointer
    readonly property string plus: "\uf317" // plus
    readonly property string plugZap2: "\uf0c7" // plug-zap-2
    readonly property string plugZap: "\uf310" // plug-zap
    readonly property string plug2: "\uf1c9" // plug-2
    readonly property string plug: "\uf36d" // plug
    readonly property string play: "\uf254" // play
    readonly property string planeLanding: "\uf366" // plane-landing
    readonly property string plane: "\uf420" // plane
    readonly property string pipette: "\uf158" // pipette
    readonly property string pinOff: "\uf07b" // pin-off
    readonly property string pin: "\uf3b0" // pin
    readonly property string pictureInPicture: "\uf511" // picture-in-picture
    readonly property string percent: "\uf25e" // percent
    readonly property string pencil: "\uf18c" // pencil
    readonly property string pencilLine: "\uf113" // pencil-line
    readonly property string pause: "\uf0bd" // pause
    readonly property string penLine: "\uf304" // pen-line
    readonly property string pen: "\uf421" // pen
    readonly property string phoneOutgoing: "\uf3c3" // phone-outgoing
    readonly property string phoneOff: "\uf157" // phone-off
    readonly property string phoneMissed: "\uf519" // phone-missed
    readonly property string phoneIncoming: "\uf10c" // phone-incoming
    readonly property string phoneForwarded: "\uf3aa" // phone-forwarded
    readonly property string phoneCall: "\uf248" // phone-call
    readonly property string phone: "\uf16f" // phone
    readonly property string panelTopClose: "\uf4fe" // panel-top-close
    readonly property string panelTopDashed: "\uf29a" // panel-top-dashed
    readonly property string panelTopOpen: "\uf360" // panel-top-open
    readonly property string panelsRightBottom: "\uf3c6" // panels-right-bottom
    readonly property string panelsLeftBottom: "\uf21c" // panels-left-bottom
    readonly property string panelsTopLeft: "\uf4b3" // panels-top-left
    readonly property string paperclip: "\uf275" // paperclip
    readonly property string paintbrushVertical: "\uf1ef" // paintbrush-vertical
    readonly property string paintbrush: "\uf0fb" // paintbrush
    readonly property string paintBucket: "\uf027" // paint-bucket
    readonly property string paintRoller: "\uf453" // paint-roller
    readonly property string panelLeftDashed: "\uf35b" // panel-left-dashed
    readonly property string panelTop: "\uf1b9" // panel-top
    readonly property string panelRightOpen: "\uf4d5" // panel-right-open
    readonly property string panelRightDashed: "\uf268" // panel-right-dashed
    readonly property string panelRightClose: "\uf580" // panel-right-close
    readonly property string panelRight: "\uf121" // panel-right
    readonly property string panelLeftOpen: "\uf167" // panel-left-open
    readonly property string panelLeftClose: "\uf230" // panel-left-close
    readonly property string panelLeft: "\uf2a5" // panel-left
    readonly property string panelBottomOpen: "\uf290" // panel-bottom-open
    readonly property string panelBottomDashed: "\uf0dd" // panel-bottom-dashed
    readonly property string panelBottomClose: "\uf021" // panel-bottom-close
    readonly property string panelBottom: "\uf315" // panel-bottom
    readonly property string notebook: "\uf00e" // notebook
    readonly property string notepadTextDashed: "\uf3da" // notepad-text-dashed
    readonly property string notepadText: "\uf100" // notepad-text
    readonly property string notebookText: "\uf32d" // notebook-text
    readonly property string notebookTabs: "\uf299" // notebook-tabs
    readonly property string notebookPen: "\uf1c8" // notebook-pen
    readonly property string nfc: "\uf4e5" // nfc
    readonly property string newspaper: "\uf343" // newspaper
    readonly property string network: "\uf1f7" // network
    readonly property string navigationOff: "\uf2da" // navigation-off
    readonly property string navigation2: "\uf028" // navigation-2
    readonly property string navigation: "\uf282" // navigation
    readonly property string music4: "\uf050" // music-4
    readonly property string music3: "\uf0db" // music-3
    readonly property string moveVertical: "\uf165" // move-vertical
    readonly property string moveUpLeft: "\uf2b5" // move-up-left
    readonly property string moveUp: "\uf025" // move-up
    readonly property string music2: "\uf11e" // music-2
    readonly property string music: "\uf50c" // music
    readonly property string moveUpRight: "\uf01a" // move-up-right
    readonly property string moveRight: "\uf0aa" // move-right
    readonly property string moveLeft: "\uf0d8" // move-left
    readonly property string moveHorizontal: "\uf1c5" // move-horizontal
    readonly property string moveDownRight: "\uf30d" // move-down-right
    readonly property string moveDownLeft: "\uf3d5" // move-down-left
    readonly property string moveDown: "\uf5a6" // move-down
    readonly property string moveDiagonal2: "\uf22a" // move-diagonal-2
    readonly property string moveDiagonal: "\uf477" // move-diagonal
    readonly property string move: "\uf474" // move
    readonly property string mousePointer: "\uf016" // mouse-pointer
    readonly property string mousePointerBan: "\uf15b" // mouse-pointer-ban
    readonly property string mousePointerClick: "\uf3cf" // mouse-pointer-click
    readonly property string mousePointer2: "\uf135" // mouse-pointer-2
    readonly property string mouseOff: "\uf382" // mouse-off
    readonly property string mouse: "\uf05f" // mouse
    readonly property string moonStar: "\uf13b" // moon-star
    readonly property string moon: "\uf023" // moon
    readonly property string monitorX: "\uf20f" // monitor-x
    readonly property string monitorUp: "\uf184" // monitor-up
    readonly property string monitorStop: "\uf316" // monitor-stop
    readonly property string monitorSpeaker: "\uf1e6" // monitor-speaker
    readonly property string minus: "\uf02f" // minus
    readonly property string monitor: "\uf033" // monitor
    readonly property string monitorCheck: "\uf1e2" // monitor-check
    readonly property string monitorDot: "\uf09c" // monitor-dot
    readonly property string monitorDown: "\uf4a1" // monitor-down
    readonly property string monitorOff: "\uf090" // monitor-off
    readonly property string monitorPause: "\uf47b" // monitor-pause
    readonly property string monitorPlay: "\uf27b" // monitor-play
    readonly property string monitorSmartphone: "\uf2e2" // monitor-smartphone
    readonly property string minimize: "\uf3de" // minimize
    readonly property string microwave: "\uf552" // microwave
    readonly property string messagesSquare: "\uf481" // messages-square
    readonly property string minimize2: "\uf56f" // minimize-2
    readonly property string micOff: "\uf133" // mic-off
    readonly property string mic: "\uf2bc" // mic
    readonly property string messageSquareX: "\uf374" // message-square-x
    readonly property string messageSquareWarning: "\uf521" // message-square-warning
    readonly property string messageSquareText: "\uf3c5" // message-square-text
    readonly property string messageSquareShare: "\uf547" // message-square-share
    readonly property string messageSquareReply: "\uf13e" // message-square-reply
    readonly property string messageSquareQuote: "\uf47f" // message-square-quote
    readonly property string messageSquarePlus: "\uf1f1" // message-square-plus
    readonly property string messageSquareOff: "\uf49a" // message-square-off
    readonly property string messageSquareMore: "\uf2e8" // message-square-more
    readonly property string messageSquareHeart: "\uf4f3" // message-square-heart
    readonly property string messageSquareDiff: "\uf27f" // message-square-diff
    readonly property string messageSquareDot: "\uf484" // message-square-dot
    readonly property string messageSquareDashed: "\uf399" // message-square-dashed
    readonly property string messageSquareCode: "\uf1b8" // message-square-code
    readonly property string messageSquare: "\uf1d5" // message-square
    readonly property string messageCircleX: "\uf0ff" // message-circle-x
    readonly property string messageCircleWarning: "\uf55e" // message-circle-warning
    readonly property string messageCircleReply: "\uf058" // message-circle-reply
    readonly property string messageCircleQuestion: "\uf587" // message-circle-question
    readonly property string messageCirclePlus: "\uf14d" // message-circle-plus
    readonly property string menu: "\uf07c" // menu
    readonly property string memoryStick: "\uf57d" // memory-stick
    readonly property string meh: "\uf408" // meh
    readonly property string messageCircle: "\uf485" // message-circle
    readonly property string messageCircleCode: "\uf103" // message-circle-code
    readonly property string messageCircleDashed: "\uf353" // message-circle-dashed
    readonly property string messageCircleHeart: "\uf534" // message-circle-heart
    readonly property string messageCircleOff: "\uf2a1" // message-circle-off
    readonly property string messageCircleMore: "\uf52e" // message-circle-more
    readonly property string megaphoneOff: "\uf56c" // megaphone-off
    readonly property string megaphone: "\uf58b" // megaphone
    readonly property string maximize2: "\uf28f" // maximize-2
    readonly property string maximize: "\uf473" // maximize
    readonly property string mapPinned: "\uf06d" // map-pinned
    readonly property string mapPinOff: "\uf215" // map-pin-off
    readonly property string map: "\uf4ad" // map
    readonly property string mapPin: "\uf110" // map-pin
    readonly property string mails: "\uf056" // mails
    readonly property string mailbox: "\uf50e" // mailbox
    readonly property string mailX: "\uf105" // mail-x
    readonly property string mailWarning: "\uf418" // mail-warning
    readonly property string mailSearch: "\uf1a7" // mail-search
    readonly property string mailQuestion: "\uf426" // mail-question
    readonly property string mailPlus: "\uf30e" // mail-plus
    readonly property string mailOpen: "\uf1b7" // mail-open
    readonly property string mailMinus: "\uf36f" // mail-minus
    readonly property string mailCheck: "\uf09f" // mail-check
    readonly property string magnet: "\uf3bd" // magnet
    readonly property string mail: "\uf3bb" // mail
    readonly property string logOut: "\uf3f6" // log-out
    readonly property string logIn: "\uf43c" // log-in
    readonly property string lockOpen: "\uf084" // lock-open
    readonly property string lockKeyholeOpen: "\uf1e3" // lock-keyhole-open
    readonly property string lockKeyhole: "\uf46e" // lock-keyhole
    readonly property string lock: "\uf43e" // lock
    readonly property string loaderCircle: "\uf3cc" // loader-circle
    readonly property string lifeBuoy: "\uf225" // life-buoy
    readonly property string loader: "\uf2d3" // loader
    readonly property string listX: "\uf2be" // list-x
    readonly property string listVideo: "\uf436" // list-video
    readonly property string listTree: "\uf2b4" // list-tree
    readonly property string listTodo: "\uf403" // list-todo
    readonly property string listStart: "\uf53a" // list-start
    readonly property string listRestart: "\uf214" // list-restart
    readonly property string listPlus: "\uf4fb" // list-plus
    readonly property string listOrdered: "\uf322" // list-ordered
    readonly property string listMusic: "\uf1bb" // list-music
    readonly property string listMinus: "\uf38a" // list-minus
    readonly property string listFilter: "\uf052" // list-filter
    readonly property string listEnd: "\uf109" // list-end
    readonly property string listCollapse: "\uf233" // list-collapse
    readonly property string listChecks: "\uf13f" // list-checks
    readonly property string list: "\uf58e" // list
    readonly property string link2Off: "\uf31a" // link-2-off
    readonly property string link2: "\uf235" // link-2
    readonly property string lightbulb: "\uf28e" // lightbulb
    readonly property string lightbulbOff: "\uf10d" // lightbulb-off
    readonly property string link: "\uf416" // link
    readonly property string lineChart: "\uf146" // line-chart
    readonly property string library: "\uf4ff" // library
    readonly property string libraryBig: "\uf2a8" // library-big
    readonly property string leaf: "\uf1f9" // leaf
    readonly property string laptop: "\uf0ea" // laptop
    readonly property string laptopMinimal: "\uf471" // laptop-minimal
    readonly property string layoutDashboard: "\uf32c" // layout-dashboard
    readonly property string layoutGrid: "\uf520" // layout-grid
    readonly property string layoutList: "\uf53d" // layout-list
    readonly property string layoutPanelLeft: "\uf2d6" // layout-panel-left
    readonly property string layoutPanelTop: "\uf226" // layout-panel-top
    readonly property string layoutTemplate: "\uf4d6" // layout-template
    readonly property string languages: "\uf446" // languages
    readonly property string laugh: "\uf463" // laugh
    readonly property string keyboard: "\uf450" // keyboard
    readonly property string japaneseYen: "\uf2c0" // japanese-yen
    readonly property string iconImport: "\uf3ac" // import
    readonly property string images: "\uf284" // images
    readonly property string imageUp: "\uf1a6" // image-up
    readonly property string imagePlus: "\uf336" // image-plus
    readonly property string imagePlay: "\uf28b" // image-play
    readonly property string imageOff: "\uf16a" // image-off
    readonly property string imageMinus: "\uf072" // image-minus
    readonly property string imageDown: "\uf4b7" // image-down
    readonly property string image: "\uf291" // image
    readonly property string hourglass: "\uf556" // hourglass
    readonly property string hotel: "\uf379" // hotel
    readonly property string home: "\uf514" // home
    readonly property string highlighter: "\uf1c4" // highlighter
    readonly property string history: "\uf047" // history
    readonly property string heartPulse: "\uf02e" // heart-pulse
    readonly property string heartOff: "\uf196" // heart-off
    readonly property string heartCrack: "\uf30b" // heart-crack
    readonly property string heart: "\uf001" // heart
    readonly property string headset: "\uf4b2" // headset
    readonly property string headphones: "\uf2fb" // headphones
    readonly property string haze: "\uf468" // haze
    readonly property string hash: "\uf31c" // hash
    readonly property string gripVertical: "\uf0ca" // grip-vertical
    readonly property string gripHorizontal: "\uf2bf" // grip-horizontal
    readonly property string grip: "\uf558" // grip
    readonly property string grid3x3: "\uf19a" // grid-3x3
    readonly property string grid2x2X: "\uf075" // grid-2x2-x
    readonly property string grid2x2Check: "\uf20d" // grid-2x2-check
    readonly property string grid2x2: "\uf0b9" // grid-2x2
    readonly property string guitar: "\uf1e5" // guitar
    readonly property string hardDriveUpload: "\uf279" // hard-drive-upload
    readonly property string hardDriveDownload: "\uf306" // hard-drive-download
    readonly property string handMetal: "\uf213" // hand-metal
    readonly property string handHelping: "\uf5b6" // hand-helping
    readonly property string handHeart: "\uf5ab" // hand-heart
    readonly property string handCoins: "\uf2e4" // hand-coins
    readonly property string github: "\uf4e7" // github
    readonly property string gitPullRequestDraft: "\uf53e" // git-pull-request-draft
    readonly property string gitPullRequestClosed: "\uf189" // git-pull-request-closed
    readonly property string gitCompareArrows: "\uf11c" // git-compare-arrows
    readonly property string gitCompare: "\uf206" // git-compare
    readonly property string gitCommitHorizontal: "\uf034" // git-commit-horizontal
    readonly property string gitCommitVertical: "\uf2e1" // git-commit-vertical
    readonly property string fullscreen: "\uf535" // fullscreen
    readonly property string gamepad: "\uf035" // gamepad
    readonly property string galleryHorizontal: "\uf00f" // gallery-horizontal
    readonly property string galleryHorizontalEnd: "\uf08b" // gallery-horizontal-end
    readonly property string galleryThumbnails: "\uf561" // gallery-thumbnails
    readonly property string galleryVertical: "\uf073" // gallery-vertical
    readonly property string galleryVerticalEnd: "\uf3b3" // gallery-vertical-end
    readonly property string ghost: "\uf58f" // ghost
    readonly property string gauge: "\uf1d6" // gauge
    readonly property string gamepad2: "\uf5a4" // gamepad-2
    readonly property string frown: "\uf331" // frown
    readonly property string flower2: "\uf2f3" // flower-2
    readonly property string focus: "\uf300" // focus
    readonly property string foldHorizontal: "\uf4e6" // fold-horizontal
    readonly property string foldVertical: "\uf0bf" // fold-vertical
    readonly property string folders: "\uf38c" // folders
    readonly property string folderX: "\uf324" // folder-x
    readonly property string folderUp: "\uf2c5" // folder-up
    readonly property string folderTree: "\uf504" // folder-tree
    readonly property string folderSync: "\uf4b4" // folder-sync
    readonly property string folderSymlink: "\uf466" // folder-symlink
    readonly property string folderMinus: "\uf22b" // folder-minus
    readonly property string folderSearch2: "\uf12a" // folder-search-2
    readonly property string folderSearch: "\uf0a4" // folder-search
    readonly property string folderRoot: "\uf46c" // folder-root
    readonly property string folderPlus: "\uf2c3" // folder-plus
    readonly property string folderPen: "\uf0a3" // folder-pen
    readonly property string folderOutput: "\uf467" // folder-output
    readonly property string folderOpenDot: "\uf097" // folder-open-dot
    readonly property string folderOpen: "\uf457" // folder-open
    readonly property string folderLock: "\uf1bd" // folder-lock
    readonly property string flower: "\uf156" // flower
    readonly property string folderClosed: "\uf15f" // folder-closed
    readonly property string folderCog: "\uf21a" // folder-cog
    readonly property string folderDot: "\uf079" // folder-dot
    readonly property string folderDown: "\uf0df" // folder-down
    readonly property string folderGit: "\uf03d" // folder-git
    readonly property string folderGit2: "\uf2f8" // folder-git-2
    readonly property string folderHeart: "\uf253" // folder-heart
    readonly property string folderInput: "\uf10f" // folder-input
    readonly property string folderKanban: "\uf1a8" // folder-kanban
    readonly property string folderKey: "\uf0ba" // folder-key
    readonly property string folderClock: "\uf1f0" // folder-clock
    readonly property string folderCheck: "\uf527" // folder-check
    readonly property string folderArchive: "\uf369" // folder-archive
    readonly property string folder: "\uf045" // folder
    readonly property string flaskConicalOff: "\uf45b" // flask-conical-off
    readonly property string flaskConical: "\uf05e" // flask-conical
    readonly property string flashlightOff: "\uf1cd" // flashlight-off
    readonly property string flashlight: "\uf591" // flashlight
    readonly property string flag: "\uf34c" // flag
    readonly property string fishOff: "\uf0a5" // fish-off
    readonly property string fish: "\uf2b6" // fish
    readonly property string fingerprint: "\uf03c" // fingerprint
    readonly property string filterX: "\uf207" // filter-x
    readonly property string filter: "\uf10e" // filter
    readonly property string film: "\uf024" // film
    readonly property string files: "\uf489" // files
    readonly property string fileX2: "\uf40b" // file-x-2
    readonly property string fileX: "\uf2c8" // file-x
    readonly property string fileWarning: "\uf3b2" // file-warning
    readonly property string fileVideo2: "\uf47a" // file-video-2
    readonly property string fileVolume2: "\uf119" // file-volume-2
    readonly property string fileVolume: "\uf3b5" // file-volume
    readonly property string fileVideo: "\uf45d" // file-video
    readonly property string fileSpreadsheet: "\uf3f4" // file-spreadsheet
    readonly property string fileStack: "\uf458" // file-stack
    readonly property string fileSymlink: "\uf508" // file-symlink
    readonly property string fileSliders: "\uf565" // file-sliders
    readonly property string fileSearch2: "\uf087" // file-search-2
    readonly property string fileTerminal: "\uf08d" // file-terminal
    readonly property string fileText: "\uf459" // file-text
    readonly property string fileType: "\uf0c5" // file-type
    readonly property string fileType2: "\uf29e" // file-type-2
    readonly property string fileUp: "\uf513" // file-up
    readonly property string fileSearch: "\uf599" // file-search
    readonly property string fileScan: "\uf476" // file-scan
    readonly property string fileQuestion: "\uf26c" // file-question
    readonly property string filePlus2: "\uf5b4" // file-plus-2
    readonly property string filePlus: "\uf17f" // file-plus
    readonly property string filePieChart: "\uf4fd" // file-pie-chart
    readonly property string filePenLine: "\uf20b" // file-pen-line
    readonly property string filePen: "\uf590" // file-pen
    readonly property string fileOutput: "\uf0d2" // file-output
    readonly property string fileMusic: "\uf143" // file-music
    readonly property string fileImage: "\uf362" // file-image
    readonly property string fileMinus2: "\uf1ad" // file-minus-2
    readonly property string fileMinus: "\uf52d" // file-minus
    readonly property string fileLock2: "\uf1f6" // file-lock-2
    readonly property string fileLock: "\uf042" // file-lock
    readonly property string fileLineChart: "\uf32b" // file-line-chart
    readonly property string fileKey2: "\uf19c" // file-key-2
    readonly property string fileKey: "\uf595" // file-key
    readonly property string fileJson2: "\uf1cc" // file-json-2
    readonly property string fileJson: "\uf015" // file-json
    readonly property string fileInput: "\uf3e8" // file-input
    readonly property string fileCheck2: "\uf381" // file-check-2
    readonly property string fileClock: "\uf4b9" // file-clock
    readonly property string fileCode: "\uf0d9" // file-code
    readonly property string fileCode2: "\uf3f0" // file-code-2
    readonly property string fileCog: "\uf442" // file-cog
    readonly property string fileDiff: "\uf09d" // file-diff
    readonly property string fileDigit: "\uf577" // file-digit
    readonly property string fileDown: "\uf23e" // file-down
    readonly property string fileHeart: "\uf54e" // file-heart
    readonly property string fileCheck: "\uf252" // file-check
    readonly property string fileBox: "\uf0ec" // file-box
    readonly property string fileBarChart2: "\uf50b" // file-bar-chart-2
    readonly property string fileBarChart: "\uf555" // file-bar-chart
    readonly property string fileBadge: "\uf2dd" // file-badge
    readonly property string fileAxis3d: "\uf038" // file-axis-3d
    readonly property string fileAudio2: "\uf48e" // file-audio-2
    readonly property string fileAudio: "\uf4bf" // file-audio
    readonly property string fileArchive: "\uf2ef" // file-archive
    readonly property string file: "\uf494" // file
    readonly property string feather: "\uf204" // feather
    readonly property string eyeOff: "\uf349" // eye-off
    readonly property string eye: "\uf15e" // eye
    readonly property string fastForward: "\uf272" // fast-forward
    readonly property string ellipsis: "\uf0f0" // ellipsis
    readonly property string ellipsisVertical: "\uf4be" // ellipsis-vertical
    readonly property string equal: "\uf503" // equal
    readonly property string equalNot: "\uf41b" // equal-not
    readonly property string externalLink: "\uf147" // external-link
    readonly property string expand: "\uf3b4" // expand
    readonly property string drama: "\uf0a9" // drama
    readonly property string draftingCompass: "\uf044" // drafting-compass
    readonly property string download: "\uf3b7" // download
    readonly property string doorOpen: "\uf406" // door-open
    readonly property string doorClosed: "\uf4e8" // door-closed
    readonly property string discAlbum: "\uf3b1" // disc-album
    readonly property string disc3: "\uf57c" // disc-3
    readonly property string disc2: "\uf5a0" // disc-2
    readonly property string disc: "\uf340" // disc
    readonly property string dices: "\uf0b0" // dices
    readonly property string dice6: "\uf2e9" // dice-6
    readonly property string dice5: "\uf348" // dice-5
    readonly property string dice4: "\uf371" // dice-4
    readonly property string dice3: "\uf413" // dice-3
    readonly property string dice2: "\uf43d" // dice-2
    readonly property string dice1: "\uf3d6" // dice-1
    readonly property string diamondPlus: "\uf2d0" // diamond-plus
    readonly property string diamondPercent: "\uf098" // diamond-percent
    readonly property string diamondMinus: "\uf05b" // diamond-minus
    readonly property string diamond: "\uf17c" // diamond
    readonly property string iconDelete: "\uf17b" // delete
    readonly property string databaseZap: "\uf33a" // database-zap
    readonly property string databaseBackup: "\uf1ff" // database-backup
    readonly property string database: "\uf4a5" // database
    readonly property string cylinder: "\uf195" // cylinder
    readonly property string cross: "\uf0f7" // cross
    readonly property string cuboid: "\uf47d" // cuboid
    readonly property string cupSoda: "\uf4c7" // cup-soda
    readonly property string cornerUpRight: "\uf57a" // corner-up-right
    readonly property string cornerUpLeft: "\uf2f0" // corner-up-left
    readonly property string cornerRightUp: "\uf596" // corner-right-up
    readonly property string cornerRightDown: "\uf3a7" // corner-right-down
    readonly property string cornerLeftUp: "\uf517" // corner-left-up
    readonly property string cornerLeftDown: "\uf1f2" // corner-left-down
    readonly property string cornerDownRight: "\uf405" // corner-down-right
    readonly property string cornerDownLeft: "\uf039" // corner-down-left
    readonly property string crop: "\uf4cf" // crop
    readonly property string cpu: "\uf32a" // cpu
    readonly property string copy: "\uf2b8" // copy
    readonly property string cookie: "\uf4cd" // cookie
    readonly property string copyX: "\uf066" // copy-x
    readonly property string copySlash: "\uf0da" // copy-slash
    readonly property string copyPlus: "\uf529" // copy-plus
    readonly property string copyMinus: "\uf424" // copy-minus
    readonly property string copyCheck: "\uf152" // copy-check
    readonly property string computer: "\uf194" // computer
    readonly property string compass: "\uf1ae" // compass
    readonly property string coffee: "\uf35c" // coffee
    readonly property string codeXml: "\uf095" // code-xml
    readonly property string code: "\uf35a" // code
    readonly property string clover: "\uf3f8" // clover
    readonly property string cloudy: "\uf0b6" // cloudy
    readonly property string cloudUpload: "\uf43a" // cloud-upload
    readonly property string cloudSunRain: "\uf0a2" // cloud-sun-rain
    readonly property string cloudSun: "\uf402" // cloud-sun
    readonly property string cloudSnow: "\uf3db" // cloud-snow
    readonly property string cloudRainWind: "\uf460" // cloud-rain-wind
    readonly property string cloudRain: "\uf18b" // cloud-rain
    readonly property string cloudOff: "\uf1de" // cloud-off
    readonly property string cloudMoonRain: "\uf352" // cloud-moon-rain
    readonly property string cloudMoon: "\uf1a5" // cloud-moon
    readonly property string cloudLightning: "\uf281" // cloud-lightning
    readonly property string cloudHail: "\uf0b8" // cloud-hail
    readonly property string cloudFog: "\uf2ca" // cloud-fog
    readonly property string cloudDrizzle: "\uf425" // cloud-drizzle
    readonly property string cloudDownload: "\uf094" // cloud-download
    readonly property string cloudCog: "\uf080" // cloud-cog
    readonly property string cloud: "\uf0d1" // cloud
    readonly property string clock12: "\uf062" // clock-12
    readonly property string clock11: "\uf0cf" // clock-11
    readonly property string clock10: "\uf064" // clock-10
    readonly property string clock7: "\uf071" // clock-7
    readonly property string clock9: "\uf5b2" // clock-9
    readonly property string clock8: "\uf560" // clock-8
    readonly property string clock6: "\uf0c9" // clock-6
    readonly property string clock5: "\uf055" // clock-5
    readonly property string clock3: "\uf122" // clock-3
    readonly property string clock2: "\uf0d5" // clock-2
    readonly property string clock1: "\uf13a" // clock-1
    readonly property string clock: "\uf177" // clock
    readonly property string clipboardX: "\uf0e0" // clipboard-x
    readonly property string clipboardType: "\uf500" // clipboard-type
    readonly property string clipboardPlus: "\uf5a5" // clipboard-plus
    readonly property string clipboardPenLine: "\uf342" // clipboard-pen-line
    readonly property string clipboardPen: "\uf515" // clipboard-pen
    readonly property string clipboardPaste: "\uf4e4" // clipboard-paste
    readonly property string clipboardMinus: "\uf314" // clipboard-minus
    readonly property string clipboardList: "\uf327" // clipboard-list
    readonly property string clipboardCopy: "\uf04b" // clipboard-copy
    readonly property string clipboardCheck: "\uf032" // clipboard-check
    readonly property string clipboard: "\uf41c" // clipboard
    readonly property string citrus: "\uf280" // citrus
    readonly property string circuitBoard: "\uf505" // circuit-board
    readonly property string circleX: "\uf16e" // circle-x
    readonly property string circleUserRound: "\uf55b" // circle-user-round
    readonly property string circleUser: "\uf181" // circle-user
    readonly property string circleEqual: "\uf4b1" // circle-equal
    readonly property string circleGauge: "\uf21b" // circle-gauge
    readonly property string circlePlay: "\uf3f2" // circle-play
    readonly property string circlePercent: "\uf4d0" // circle-percent
    readonly property string circlePause: "\uf057" // circle-pause
    readonly property string circleSlash2: "\uf4cb" // circle-slash-2
    readonly property string circleSlash: "\uf32e" // circle-slash
    readonly property string circlePlus: "\uf1ea" // circle-plus
    readonly property string circlePower: "\uf50f" // circle-power
    readonly property string circleOff: "\uf088" // circle-off
    readonly property string circleDivide: "\uf358" // circle-divide
    readonly property string circleEllipsis: "\uf115" // circle-ellipsis
    readonly property string circleFadingPlus: "\uf305" // circle-fading-plus
    readonly property string circleArrowOutUpRight: "\uf245" // circle-arrow-out-up-right
    readonly property string circleArrowOutUpLeft: "\uf128" // circle-arrow-out-up-left
    readonly property string circleArrowOutDownRight: "\uf2b1" // circle-arrow-out-down-right
    readonly property string circleArrowOutDownLeft: "\uf2cf" // circle-arrow-out-down-left
    readonly property string circleCheckBig: "\uf540" // circle-check-big
    readonly property string circleCheck: "\uf364" // circle-check
    readonly property string circleArrowUp: "\uf0f3" // circle-arrow-up
    readonly property string circleArrowRight: "\uf217" // circle-arrow-right
    readonly property string circleArrowLeft: "\uf389" // circle-arrow-left
    readonly property string circleArrowDown: "\uf19e" // circle-arrow-down
    readonly property string circleAlert: "\uf4aa" // circle-alert
    readonly property string cigaretteOff: "\uf139" // cigarette-off
    readonly property string cigarette: "\uf44c" // cigarette
    readonly property string cherry: "\uf002" // cherry
    readonly property string chevronUp: "\uf46b" // chevron-up
    readonly property string chevronRight: "\uf41e" // chevron-right
    readonly property string chevronLeft: "\uf026" // chevron-left
    readonly property string chevronDown: "\uf4fa" // chevron-down
    readonly property string checkCheck: "\uf4ac" // check-check
    readonly property string check: "\uf313" // check
    readonly property string cat: "\uf081" // cat
    readonly property string cast: "\uf34f" // cast
    readonly property string caseUpper: "\uf2cc" // case-upper
    readonly property string caseSensitive: "\uf301" // case-sensitive
    readonly property string caseLower: "\uf4d7" // case-lower
    readonly property string cameraOff: "\uf49f" // camera-off
    readonly property string camera: "\uf236" // camera
    readonly property string calendarX2: "\uf3d9" // calendar-x-2
    readonly property string calendarX: "\uf0be" // calendar-x
    readonly property string calendarSearch: "\uf4b8" // calendar-search
    readonly property string calendarRange: "\uf270" // calendar-range
    readonly property string calendarPlus2: "\uf4d8" // calendar-plus-2
    readonly property string calendarPlus: "\uf3fb" // calendar-plus
    readonly property string calendarOff: "\uf51c" // calendar-off
    readonly property string calendarMinus2: "\uf013" // calendar-minus-2
    readonly property string calendarMinus: "\uf11b" // calendar-minus
    readonly property string calendarHeart: "\uf0ef" // calendar-heart
    readonly property string calendarFold: "\uf4f4" // calendar-fold
    readonly property string calendarDays: "\uf009" // calendar-days
    readonly property string calendarClock: "\uf0a6" // calendar-clock
    readonly property string calendarCheck2: "\uf4f8" // calendar-check-2
    readonly property string calendarCheck: "\uf3e4" // calendar-check
    readonly property string calendar: "\uf102" // calendar
    readonly property string bug: "\uf1ba" // bug
    readonly property string bugOff: "\uf548" // bug-off
    readonly property string bugPlay: "\uf1d4" // bug-play
    readonly property string brainCircuit: "\uf166" // brain-circuit
    readonly property string brush: "\uf3fa" // brush
    readonly property string bellRing: "\uf176" // bell-ring
    readonly property string bellPlus: "\uf3a9" // bell-plus
    readonly property string bellOff: "\uf125" // bell-off
    readonly property string bellMinus: "\uf443" // bell-minus
    readonly property string bellDot: "\uf0e1" // bell-dot
    readonly property string bell: "\uf35f" // bell
    readonly property string batteryWarning: "\uf431" // battery-warning
    readonly property string batteryMedium: "\uf390" // battery-medium
    readonly property string batteryLow: "\uf261" // battery-low
    readonly property string batteryFull: "\uf318" // battery-full
    readonly property string batteryCharging: "\uf38e" // battery-charging
    readonly property string battery: "\uf346" // battery
    readonly property string barChart: "\uf44a" // bar-chart
    readonly property string ban: "\uf438" // ban
    readonly property string arrowUpToLine: "\uf4a2" // arrow-up-to-line
    readonly property string arrowRightToLine: "\uf070" // arrow-right-to-line
    readonly property string arrowRightLeft: "\uf559" // arrow-right-left
    readonly property string arrowUpDown: "\uf00b" // arrow-up-down
    readonly property string arrowDownLeft: "\uf45a" // arrow-down-left
    readonly property string arrowDownRight: "\uf0ed" // arrow-down-right
    readonly property string arrowUp: "\uf129" // arrow-up
    readonly property string arrowLeftToLine: "\uf344" // arrow-left-to-line
    readonly property string arrowRightFromLine: "\uf0fe" // arrow-right-from-line
    readonly property string arrowUpFromLine: "\uf525" // arrow-up-from-line
    readonly property string arrowUpLeft: "\uf501" // arrow-up-left
    readonly property string arrowUpRight: "\uf228" // arrow-up-right
    readonly property string arrowUpNarrowWide: "\uf43f" // arrow-up-narrow-wide
    readonly property string arrowLeftRight: "\uf096" // arrow-left-right
    readonly property string arrowRight: "\uf401" // arrow-right
    readonly property string arrowLeft: "\uf0fc" // arrow-left
    readonly property string arrowDownUp: "\uf3e0" // arrow-down-up
    readonly property string arrowDownToLine: "\uf2ae" // arrow-down-to-line
    readonly property string arrowDownNarrowWide: "\uf123" // arrow-down-narrow-wide
    readonly property string arrowDownFromLine: "\uf2ed" // arrow-down-from-line
    readonly property string arrowDownAZ: "\uf168" // arrow-down-a-z
    readonly property string arrowDown: "\uf598" // arrow-down
    readonly property string arrowBigUp: "\uf0e6" // arrow-big-up
    readonly property string arrowBigRight: "\uf3b9" // arrow-big-right
    readonly property string arrowBigLeft: "\uf171" // arrow-big-left
    readonly property string arrowBigDown: "\uf537" // arrow-big-down
    readonly property string archiveX: "\uf479" // archive-x
    readonly property string archiveRestore: "\uf396" // archive-restore
    readonly property string archive: "\uf3c8" // archive
    readonly property string appWindow: "\uf278" // app-window
    readonly property string annoyed: "\uf523" // annoyed
    readonly property string angry: "\uf04a" // angry
    readonly property string alignHorizontalJustifyStart: "\uf52a" // align-horizontal-justify-start
    readonly property string alignHorizontalJustifyEnd: "\uf1ac" // align-horizontal-justify-end
    readonly property string alignEndHorizontal: "\uf329" // align-end-horizontal
    readonly property string alignStartHorizontal: "\uf086" // align-start-horizontal
    readonly property string alarmClockPlus: "\uf47c" // alarm-clock-plus
    readonly property string alarmClockOff: "\uf37c" // alarm-clock-off
    readonly property string alarmClockMinus: "\uf21d" // alarm-clock-minus
    readonly property string alarmClockCheck: "\uf507" // alarm-clock-check
    readonly property string alarmClock: "\uf37d" // alarm-clock
    readonly property string activity: "\uf114" // activity

    function byName(name) {
        const key = String(name || "").replace(/^icon-/, "").split(/[-_]/).map((part, index) => index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)).join("");
        const safeKey = key in root ? key : `icon${key.charAt(0).toUpperCase()}${key.slice(1)}`;
        return root[safeKey] || "";
    }
}
