#!/usr/bin/env python3

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path


def state_root() -> Path:
    return Path(os.environ.get("XDG_STATE_HOME", Path.home() / ".local/state")) / "quickshell/theme"


def load_mode(root: Path) -> str:
    try:
        mode = (root / "mode").read_text(encoding="utf-8").strip()
    except OSError:
        return "dark"
    return mode if mode in {"dark", "light"} else "dark"


def load_palette(root: Path, mode: str) -> dict[str, object]:
    palette_path = root / "palette.json"
    data = json.loads(palette_path.read_text(encoding="utf-8"))
    themed = data.get(mode)
    return themed if isinstance(themed, dict) else data


def hex_to_rgb(hex_color: object, fallback: str = "#8aadf4") -> tuple[int, int, int]:
    value = str(hex_color or "#8aadf4").strip().lstrip("#")
    if len(value) == 8:
        value = value[:6]
    if len(value) != 6:
        value = fallback.strip().lstrip("#")
    try:
        return tuple(int(value[i : i + 2], 16) for i in (0, 2, 4))
    except ValueError:
        fallback_value = fallback.strip().lstrip("#")
        return tuple(int(fallback_value[i : i + 2], 16) for i in (0, 2, 4))


def rgb_to_hex(rgb: tuple[int, int, int]) -> str:
    return "{:02x}{:02x}{:02x}".format(*rgb)


def luminance(rgb: tuple[int, int, int]) -> float:
    r, g, b = [channel / 255 for channel in rgb]
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def mix(a: tuple[int, int, int], b: tuple[int, int, int], ratio: float) -> tuple[int, int, int]:
    return tuple(round((1 - ratio) * x + ratio * y) for x, y in zip(a, b, strict=True))


def ensure_min_luminance(rgb: tuple[int, int, int], minimum: float) -> tuple[int, int, int]:
    value = rgb
    for _ in range(10):
        if luminance(value) >= minimum:
            return value
        value = mix(value, (255, 255, 255), 0.12)
    return value


def ensure_max_luminance(rgb: tuple[int, int, int], maximum: float) -> tuple[int, int, int]:
    value = rgb
    for _ in range(10):
        if luminance(value) <= maximum:
            return value
        value = mix(value, (0, 0, 0), 0.12)
    return value


def border_colors(palette: dict[str, object], mode: str) -> tuple[tuple[int, int, int], tuple[int, int, int]]:
    accent = hex_to_rgb(palette.get("accent"))
    accent2 = hex_to_rgb(palette.get("accent2"), "#c6a0f6")

    if mode == "light":
        first = ensure_max_luminance(mix(accent, (0, 0, 0), 0.22), 0.44)
        second = ensure_max_luminance(mix(accent2, (0, 0, 0), 0.28), 0.46)
    else:
        first = ensure_min_luminance(mix(accent, (255, 255, 255), 0.36), 0.54)
        second = ensure_min_luminance(mix(accent2, (255, 255, 255), 0.22), 0.58)

    return first, second


def rgba(rgb: tuple[int, int, int], alpha: str) -> str:
    value = rgb_to_hex(rgb)
    return f"rgba({value}{alpha})"


def write_lua(root: Path, active_start: str, active_end: str, inactive_start: str, inactive_end: str) -> None:
    output = Path.home() / ".config/quickshell/generated/hyprland/borders.lua"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        "\n".join(
            [
                "-- Generated by quickshell/scripts/theme/apply_hyprland.py",
                "return {",
                f'  active_border = {{ colors = {{ "{active_start}", "{active_end}" }}, angle = 50 }},',
                f'  inactive_border = {{ colors = {{ "{inactive_start}", "{inactive_end}" }}, angle = 50 }},',
                "}",
                "",
            ]
        ),
        encoding="utf-8",
    )


def hypr_keyword(name: str, value: str) -> None:
    subprocess.run(
        ["hyprctl", "keyword", name, value],
        check=False,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )


def hypr_reload() -> None:
    subprocess.run(
        ["hyprctl", "reload"],
        check=False,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )


def main() -> int:
    root = state_root()
    mode = sys.argv[1] if len(sys.argv) > 1 and sys.argv[1] in {"dark", "light"} else load_mode(root)

    try:
        palette = load_palette(root, mode)
        first, second = border_colors(palette, mode)
        active_start = rgba(first, "f2")
        active_end = rgba(second, "f2")
        inactive_start = rgba(first, "66")
        inactive_end = rgba(second, "66")
    except Exception:
        return 1

    write_lua(root, active_start, active_end, inactive_start, inactive_end)
    if shutil.which("hyprctl") is None:
        return 0

    hypr_keyword("general:col.active_border", f"{active_start} {active_end} 50deg")
    hypr_keyword("general:col.inactive_border", f"{inactive_start} {inactive_end} 50deg")
    hypr_reload()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
