foreground #d7d4e2
background #18141f
selection_foreground #d7d4e2
selection_background #3a2a3d
cursor #d7d4e2
cursor_text_color #18141f
active_border_color #a16d97
inactive_border_color #45384f
color0 #16131d
color1 #86617f
color2 #8b7f8e
color3 #b592b2
color4 #ba9dba
color5 #6f566b
color6 #a39aa8
color7 #d7d4e2
color8 #312839
color9 #a38aa2
color10 #a69eac
color11 #c2aac4
color12 #c8b7cd
color13 #9f90a1
color14 #bbb5c3
color15 #ffffff
